
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.76/sell?characterEncoding=utf-8&useSSL=false&&serverTimezone=UTC
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null

server:
  servlet:
    context-path: /sell

wechat:
  mpAppId: wxd898fcb01713c658
#  mpAppId: wxcd727d4b6740696a # 我自己的
  mpAppSecret: 562d3fdf26d1e95174202bb0864451d8

  mchId: 1483469312
  mchKey: 098F6BCD4621D373CADE4E832627B4F6
  keyPath: /Users/mosiqi/food-order-app/doc/h5.p12
  notifyUrl: http://mosiqi.natapp1.cc/sell/pay/notify
